### ISSUE TITLE
BUG - Redirect to / in firefox with watchLoggedIn true at any non index

### ISSUE THREAD

**Issue by aldarund** [nuxt-community/auth-module#80]
With default watchLoggedIn: true in FF every request to any url will be redirected to /.
It only happens on first load, clicking links within app work fine. But on first load you will be just redirected to / . Even with user logged in. 
Chrome works fine without redirect
It happens without any use of auth middleware ( so there shouldnt be any redirect at all).
mode - spa.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c59">#c59</a>)</em></sub></div>

**Comment by aldarund** [comment]
Same with dev branch with strategies, although watchLoggedIn false doesnt work anymore and neither work setting 
```
redirect: {
      logout: false,
      login: false,
      callback: false
    },
```
Chrome still fine and problem still only in ff

Disabling nuxt/auth module fixes redirect issue.

**Comment by aldarund** [comment]
@breakingrobot Figured out a bit .
redirect: false in options fixes the issue.
The redirect itself caused by trigger of autoRedirect function
https://github.com/nuxt-community/auth-module/blob/dev/lib/auth/auth.js#L35

**Comment by breakingrobot** [comment]
@aldarund Hi !

I would like to know if this issue persist with the stable release of 4.0, could you confirm this ? 👍

**Comment by aldarund** [comment]
@breakingrobot Cant check in 4.0 because of https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c83

**Comment by breakingrobot** [comment]
@aldarund Could you try using the `dev` branch please, I merged fixes recently 👍

**Comment by aldarund** [comment]
@breakingrobot second issue with scheme/local gone. But still have first issue with using custom scheme

**Comment by breakingrobot** [comment]
@aldarund Could you post your custom scheme as a Gist or link to a reproduction way :) ?

**Comment by aldarund** [comment]
@breakingrobot https://gist.github.com/aldarund/e6f030287057dc056732b1875eb11297
nuxt config:
```
auth: {
    strategies: {
       apollo: {
         _scheme: '~/apollo/auth/strategy.js'
      }
    },
    redirect: false
  },
```
I dont think scheme itself relevant. It fails on build on resolveProvider it doesnt even touch scheme as far as i understand.

**Comment by breakingrobot** [comment]
@aldarund Can you paste the build error stack on `resolverProvider` 👍 ?

**Comment by aldarund** [comment]
@breakingrobot https://gist.github.com/aldarund/4f5363b8f5de4d139318fd27890adb47

**Comment by breakingrobot** [comment]
@aldarund I assume `Error: Cannot find module 'C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\apollo'` does exist, is that right ?

**Comment by aldarund** [comment]
@breakingrobot yes. https://i.imgur.com/IRgFGoH.png
```
 Directory of C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\apollo\auth

03.04.2018  15:36    <DIR>          .
03.04.2018  15:36    <DIR>          ..
03.04.2018  15:36             1 034 strategy.js
```

**Comment by breakingrobot** [comment]
Your build error seems to report the wrong path:

> Error: Cannot find module 'C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\apollo'

Shouldn't it be:
> 'C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\apollo\auth\strategy'

Going to investigate why the resolution gave the wrong path.

**Comment by aldarund** [comment]
@breakingrobot As i understand it doesnt even touch _scheme ( resolveScheme doesnt trigger for custom scheme ) property but rather try to find a provider from a strategy name, so hence it tries apollo dir.
Heh, found something interesting. If i change strategy name  to following:
```
    strategies: {
      xxxx: {
        _scheme: '~/apollo/auth/strategy.js'
      }
```
All compiles fine. So it seems to be confused by existence of directory with same name as a strategy

**Comment by aldarund** [comment]
@breakingrobot i have tested with renamed folder to workaround resolve issue. Original issue still persist. It happens only in SPA mode and only in FF ( maybe in some other browsers but i tested only in chrome and FF, chrome fine - FF redirect). In server mode works fine.

**Comment by breakingrobot** [comment]
@aldarund We know why the issue happens and are going to fix it with @pi0 ;)

**Comment by chuckcharles** [comment]
I have this same issue even after 4.3.0. Only in FF.

**Comment by subsociety** [comment]
Same here, still seeing the same issue after updating to 4.3.0.  In Firefox, the `this.ctx.from` value is populated on subsequent page loads, prohibiting the early return condition from triggering.

```
// Disable redirect on refresh / direct load of a page.
if (loggedIn && !_this.ctx.from) {
  return;
}
```

**Comment by pi0** [comment]
This problem should finally be fixed with 4.5.0. `watchLoggedIn` was called too early before the strategy is ready. Also `watchLoggedIn` option support added back so we can entirely disable it.

https://github.com/nuxt-community/auth-module/releases/tag/v4.5.0
